services:
  musicbot:
    build: .
    container_name: musicbot
    restart: always
    volumes:
      - ./:/app

  lavalink:
    image: fredboat/lavalink:dev-alpine
    container_name: lavalink
    restart: always
    user: 1000:1000
    environment:
      - _JAVA_OPTIONS=-Xmx1G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    ports:
      - 2333:2333
    volumes:
      - ./lavalink/application.yaml:/opt/Lavalink/application.yml
      - ./lavalink/plugins/:/opt/Lavalink/plugins/